# cython: language_level=3
cimport cython
from raysect.optical cimport Spectrum, Point3D
from numpy cimport ndarray

from raysect.core.math.cython cimport integrate, interpolate
from numpy cimport PyArray_SimpleNew, PyArray_FILLWBYTE, NPY_FLOAT64, npy_intp, import_array

# required by numpy c-api
import_array()


cdef class OpaqueSpectrum(Spectrum):

    def __init__(self, double min_wavelength, double max_wavelength, int bins):
        self._wavelength_check(min_wavelength, max_wavelength)
        self.prev_init = False
        if bins < 1:
            raise ValueError("Number of bins cannot be less than 1.")

        self._construct(min_wavelength, max_wavelength, bins)


    def __getstate__(self):
        """Encodes state for pickling."""

        return (
            self.absorbances,
            super().__getstate__()
        )

    def __setstate__(self, state):
        """Decodes state for pickling."""

        (
            self.min_wavelength,
            self.max_wavelength,
            self.bins,
            self.delta_wavelength,
            self.samples,
            self._wavelengths,
            super_state
        ) = state
        super().__setstate__(super_state)

        # rebuild memory views
        self.samples_mv = self.samples
        self.absorbances_mv = self.absorbances

    # must override automatic __reduce__ method generated by cython for the base class
    def __reduce__(self):
        return self.__new__, (self.__class__, ), self.__getstate__()

    
    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.cdivision(True)
    cdef void _construct(self, double min_wavelength, double max_wavelength, int bins):

        cdef npy_intp size, index

        self.min_wavelength = min_wavelength
        self.max_wavelength = max_wavelength
        self.bins = bins
        self.delta_wavelength = (max_wavelength - min_wavelength) / bins

        # create spectral sample bins, initialise with zero
        size = bins
        self.samples = PyArray_SimpleNew(1, &size, NPY_FLOAT64)
        PyArray_FILLWBYTE(self.samples, 0)

        self.absorbances = PyArray_SimpleNew(1, &size, NPY_FLOAT64)
        PyArray_FILLWBYTE(self.absorbances, 0)

        # obtain memory view
        self.absorbances_mv = self.absorbances

        # wavelengths is populated on demand
        self._wavelengths = None

    
    cpdef OpaqueSpectrum _new_spectrum(self):
        """
        Returns a new Spectrum compatible with the same spectral settings.

        :rtype: Spectrum
        """

        return new_spectrum(self.min_wavelength, self.max_wavelength, self.bins)

    cpdef Spectrum new_spectrum(self):
        return self._new_spectrum()

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cpdef OpaqueSpectrum copy(self):
        """
        Returns a copy of the spectrum.

        :rtype: OpaqueSpectrum
        """

        cdef:
            OpaqueSpectrum spectrum
            npy_intp index

        spectrum = self.new_spectrum()
        for index in range(self.samples_mv.shape[0]):
            spectrum.samples_mv[index] = self.samples_mv[index]
        return spectrum

    # low level scalar maths functions
    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cdef void add_scalar(self, double value) nogil:

        cdef npy_intp index
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] += value

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cdef void sub_scalar(self, double value) nogil:

        cdef npy_intp index
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] -= value

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cdef void mul_scalar(self, double value) nogil:

        cdef npy_intp index
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] *= value

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.cdivision(True)
    @cython.initializedcheck(False)
    cdef void div_scalar(self, double value) nogil:

        cdef:
            double reciprocal
            npy_intp index

        reciprocal = 1.0 / value
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] *= reciprocal

    # low level array maths functions
    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cdef void add_array(self, double[::1] array) nogil:

        cdef npy_intp index
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] += array[index]

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cdef void sub_array(self, double[::1] array) nogil:

        cdef npy_intp index
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] -= array[index]

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.initializedcheck(False)
    cdef void mul_array(self, double[::1] array) nogil:

        cdef npy_intp index
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] *= array[index]

    @cython.boundscheck(False)
    @cython.wraparound(False)
    @cython.cdivision(True)
    @cython.initializedcheck(False)
    cdef void div_array(self, double[::1] array) nogil:

        cdef npy_intp index
        for index in range(self.samples_mv.shape[0]):
            self.samples_mv[index] /= array[index]

cdef OpaqueSpectrum new_spectrum(double min_wavelength, double max_wavelength, int bins):

    cdef OpaqueSpectrum v

    v = OpaqueSpectrum.__new__(OpaqueSpectrum)
    v._construct(min_wavelength, max_wavelength, bins)

    return v
